<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 12/01/2018
 * Time: 10:15 AM
 */
/** @var Clientes $this */
?>
<div class="padding">
    <div class="box row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped b-t b-b" width="100%">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Original</th>
                        <th class="none">Bitcoin Cash</th>
                        <th class="none">Bitcoin</th>
                        <th class="none">Ethereum</th>
                        <th class="none">Litecoin</th>
                        <th class="none">Ripple</th>
                        <th>Actual</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?= $this->tablaClientes ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
