<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 08/08/2017
 * Time: 12:31 PM
 */
?>
<div class="padding">
    <div class="form-group row m-t-md">
        <div class="col-xs-12">
            Direccion ETH
        </div>
        <div class="col-xs-6">
            <div class="col-xs-10">
                <input name="direccionEth" placeholder="ETH" type="text" class="form-control" value="<?= $this->eth ?>">
            </div>
            <div class="col-xs-2">
                <a onclick="btnGuardarEth()" class="btn blue-500">Guardar</a>
            </div>
        </div>
    </div>
    <hr>
    <div class="form-group row m-t-md">
        <div class="col-md-3">
            <a class="btn btn-primary col-md-12"
               onclick="aside('config','api')">Cambiar API</a>
        </div>
    </div>
</div>
