<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 06/abr/2017
 * Time: 06:02 PM
 */
$this->idioma = Globales::getIdioma('transacciones');
?>
<div>
    <a class="floatingButton md-btn md-fab md-fab-bottom-right pos-fix lime-600">
        <i class="material-icons i-24 text-white">add</i>
    </a>
    <div class="quickMenu hidden" id="quickMenu" data-backdrop="false">
        <div class="right" style="width: 207px">
            <div class="box" style="float:left">
                <div class="box-body">
                    <?php if ($_SESSION["namespace"] != "distribuidor\\"): ?>
                        <div class="row">
                        <span style="cursor: pointer" onclick=""
                              class="label label-lg pink-500"></span>
                        </div>
                        <div class="row">
                        <span style="cursor: pointer" onclick=""
                              class="label label-lg light-green-500"></span>
                        </div>
                        <div class="row">
                        <span style="cursor: pointer" onclick=""
                              class="label label-lg accent"></span>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <!--
            <div class="box" style="float:right">
                <div class="box-body">
                    <div class="row">
                        <a onclick="aside('transacciones','nuevo',{tipo:2})"
                           class="btn btn-icon pink-500">
                            <i class="material-icons">remove</i>
                        </a>
                    </div>
                    <div class="row">
                        <a onclick="aside('transacciones','nuevo',{tipo:1})"
                           class="btn btn-icon light-green-500">
                            <i class="material-icons">add</i>
                        </a>
                    </div>
                    <div class="row">
                        <a onclick="aside('transacciones','nuevo',{tipo:3})"
                           class="btn btn-icon accent">

                            <i class="material-icons">swap_horiz</i>
                        </a>
                    </div>
                </div>
            </div>-->
        </div>
    </div>
</div>
