<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 24/08/2017
 * Time: 02:02 PM
 */
/** @var Orders $this */
?>
<div class="padding">
    <div class="box">
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped b-t b-b" width="100%">
                        <thead>
                        <tr>
                            <th>Monto</th>
                            <th>Cantidad</th>
                            <th>Moneda</th>
                            <th>Tipo</th>
                            <th>Precio</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?= $this->tablaOrdenes ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
