<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 27/feb/2017
 * Time: 05:37 PM
 */
?>
<div class="content-header">
    <!-- link and dropdown -->
    <ul class="nav navbar-nav">
        <li class="nav-item acciones">
            <?php if ($this->permisos->$_SESSION["modulo"]->nuevo): ?>
                <a onclick="navegar('<?= $_SESSION["modulo"] ?>','nuevo');"
                   class="btn btn-primary" data-toggle="dropdown">
                    <i class="fa fa-fw fa-plus text-muted"></i>
                    <span><?= $idioma->btnNuevo ?></span>
                </a>
            <?php endif; ?>
        </li>
    </ul>
</div>
<div class="padding">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="table-responsive">
                    <table class="table table-striped b-t b-b">
                        <thead>
                        <tr>
                            <th><?= $idioma->lblNombre ?></th>
                            <th style="width: 1px"><?= $idioma->lblAcciones ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?= $this->tablaPerfiles ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
