<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 04/08/2017
 * Time: 01:52 PM
 */
/** @var Wallet $this */
?>
<div class="padding">
    <div class="box">
        <div class="row">
            <div class="col-md-12">
                <label>Ultima Actualización: <?=date('Y-m-d h:i:sa')?></label>
            </div>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped b-t b-b" width="100%">
                        <thead>
                        <tr>
                            <th class="all">Moneda</th>
                            <th>Cantidad</th>
                            <th class="none">Inversión Inicial</th>
                            <th class="desktop">Precio Inicial</th>
                            <th>Precio Actual</th>
                            <th class="all">Valor</th>
                            <th class="all">G/P</th>
                            <th class="desktop">%</th>
                            <th class="desktop">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?= $this->tablaMonedas ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="form-group">
                    <div class="col-md-4">
                        <h6>Disponible: <?= Globales::formato_moneda("$", $this->disponible->available) ?></h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-4">
                        <h6>Total: <?= Globales::formato_moneda("$", $this->disponible->total)?></h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-4">
                        <h6>En ordenes: <?= Globales::formato_moneda("$", $this->disponible->locked) ?></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>