<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 20/feb/2017
 * Time: 01:04 PM
 */
/** @var Control $this */
?>
<html>
<head>
    <meta charset="utf-8"/>
    <title>.::CryptoWallet::.</title>
    <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- for ios 7 style, multi-resolution icon of 152x152 -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
    <link rel="apple-touch-icon" href="<?= HTTP_PATH_ROOT ?>recursos/img/logo.png">
    <meta name="apple-mobile-web-app-title" content="Flatkit">
    <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" sizes="196x196" href="<?= HTTP_PATH_ROOT ?>recursos/img/logo.png">

    <?= $this->stylesheets ?>
</head>
<body>
<div class="loader">
    <div id="loading">
        <div class="loading-center">
            <div class="loading-center-absolute">
                <div class="object" id="object_one"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_four"></div>
                <div class="object" id="object_five"></div>
                <div class="object" id="object_six"></div>
                <div class="object" id="object_seven"></div>
                <div class="object" id="object_eight"></div>
                <div class="object" id="object_big"></div>
            </div>
        </div>
    </div>
</div>
<form id="frmSistema">
    <fieldset id="loader" disabled>
        <link rel="shortcut icon" sizes="196x196" href="/recursos/plugins/flatkit/assets/images/logo.png">
        <div class="app" id="app">
            <?php if ($vista != "login" and $vista != "registro"): ?>
            <!-- ############ LAYOUT START-->
            <!-- aside -->
            <div id="aside" class="app-aside modal fade nav-dropdown">
                <!-- fluid app aside -->
                <div class="left navside dark dk" layout="column">
                    <div class="navbar no-radius">
                        <!-- brand -->
                        <a class="navbar-brand" onclick="navegar('inicio')">
                            <img src="<?= HTTP_PATH_ROOT ?>recursos/img/logo.png" alt="Logo">
                            <span class="hidden-folded inline">CRYPTO</span>
                        </a>
                        <div>
                            <a onclick="btnMiPerfil()">
                                <span class="nombreUser hidden-folded inline text-muted nav-text"><?= $this->nombreUsuario ?></span></a>
                        </div>
                        <!-- / brand -->
                    </div>
                    <div flex class="hide-scroll">
                        <nav class="scroll nav-light">
                            <ul class="nav" ui-nav>
                                <?= $this->modulos ?>
                                <?php if ($_SESSION["namespace"] == "\\"): ?>
                                    <!--<li class="nav-header hidden-folded pagar">
                                    <span class="nav-icon">
                                    </span>
                                        <a onclick="navegar('pago');">
                                            <span class="nav-text">Suscripción</span>
                                        </a>
                                    </li>-->
                                <?php endif; ?>
                            </ul>
                        </nav>
                    </div>
                    <div flex-no-shrink class="b-t navside">
                        <div class="nav-header">
                            <span class="nav-icon"><i class="material-icons">help</i></span>
                            <a class="nav-text" href="" target="_blank">Ayuda</a>
                        </div>
                    </div>
                    <div flex-no-shrink class="b-t">
                        <div class="nav-fold">
                            <span class="version">v/<?= Globales::$version ?>
                                -<?= $_SESSION[token] ?></span>
                        </div>
                    </div>
                </div>
            </div>
        <!-- / -->
        <!-- content -->
            <div id="content" class="app-content box-shadow-z0" role="main">
                <div class="app-header white box-shadow">
                    <div id="messages" class="animated" style="opacity: 0;display: none;">
                        <ul>
                            <li></li>
                        </ul>
                    </div>
                    <div class="navbar">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a onclick="navegar('inicio')" class="navbar-brand nav-link">
                                    <img src="<?= HTTP_PATH_ROOT ?>recursos/img/logo.png" alt="Logo">
                                </a>
                            </li>
                        </ul>
                        <!-- Open side - Naviation on mobile -->
                        <a data-toggle="modal" data-target="#aside" class="navbar-item pull-left hidden-lg-up">
                            <i class="material-icons">&#xe5d2;</i>
                        </a>
                        <!-- / -->

                        <!-- Page title - Bind to $state's title -->
                        <div class="navbar-item pull-left h5" ng-bind="$state.current.data.title" id="pageTitle"></div>

                        <!-- navbar right -->
                        <ul class="nav navbar-nav pull-right">
                            <li class="nav-item dropdown pos-stc-xs">
                                <a class="nav-link" href data-toggle="dropdown">
                                    <i class="material-icons">&#xe7f5;</i>
                                    <span class="label label-sm up warn"><?= $this->numNot ?></span>
                                </a>
                                <div class="dropdown-menu pull-right w-xl animated fadeInUp no-bg no-border no-shadow">
                                    <?= $this->listNotifications ?>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link clear dropdown-toggle"
                                   data-toggle="dropdown" role="button"
                                   aria-haspopup="true" aria-expanded="false">
                                    <span class="avatar w-32">
                                        <img src="<?= HTTP_PATH_ROOT ?>recursos/img/user.png" alt="user">
                                        <i class="on b-white bottom"></i>
                                    </span>
                                </a>
                                <div class="dropdown-menu pull-right dropdown-menu-scale">
                                    <a class="dropdown-item" onclick="btnMiPerfil()">Perfil</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" onclick="cerrarSesion()">Cerrar Sesión</a>
                                </div>
                            </li>
                        </ul>
                        <!-- / navbar right -->

                        <!-- navbar collapse
                        <div class="collapse navbar-toggleable-sm" id="collapse">
                            <div ui-include="'recursos/plugins/flatkit/views/blocks/navbar.form.right.html'"></div>
                        </div>
                        <!-- / navbar collapse -->
                    </div>
                </div><!--
                <div class="app-footer">
                    <div class="p-a text-xs">
                        <div class="pull-right text-muted">
                            <strong>Eleven TI</strong> &copy; <?= date('Y') ?> <span
                                    class="hidden-xs-down">- Built with Love v<?= $version ?></span>
                            <a ui-scroll-to="content"><i class="fa fa-long-arrow-up p-x-sm"></i></a>
                        </div>
                    </div>
                </div>-->
                <div ui-view class="app-body" id="view">

                    <?php
                    $namespace = Globales::$namespace;
                    #include_once HTTP_PATH_ROOT . "vista/floatingButton.phtml"
                    ?>

                    <?php endif; ?>

                    <?= $this->page ?>

                    <?php if ($vista != "login" and $vista != "registro"): ?>
                </div>
            </div>
            <!-- / -->
            <!-- ############ LAYOUT END-->
        <?php endif; ?>
        </div>
    </fieldset>
</form>
<form id="frmAside">
    <!-- right -->
    <div class="modal fade inactive" id="rightBar" data-backdrop="false">
        <div class="right w-xl b-l white">
            <div class="navbar grey-100">
                <a class="btn btn-danger btn-sm btnAside" onclick="cerrarAside()">
                    <i class="material-icons">close</i>
                </a>
            </div>
            <input type="hidden" id="txtAside" value="0">
            <div id="rightBarContent">
                <div class="loading"></div>
            </div>
        </div>
    </div>
</form>
<?= $this->scripts ?>
</body>
</html>
