<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 18/08/2017
 * Time: 11:54 AM
 */
?>
<div class="center-block w-xxl w-auto-xs">
    <div class="p-a-md box-color r text-color m-a">
        <div class="md-form-group float-label">
            <input type="text" class="md-input has-value" readonly
                   value="<?= $this->moneda->nombre ?>">
            <input name="book" type="hidden" class="md-input has-value"
                   value="<?= $this->moneda->book ?>">
            <label>Moneda</label>
        </div>
        <div class="md-form-group float-label">
            <input name="cantidad" type="text" class="md-input has-value"
                   value="<?= $this->moneda->cantidad ?>">
            <label>Cantidad</label>
        </div>
        <div class="md-form-group float-label">
            <input name="costo" type="text" class="md-input has-value"
                   value="<?= $this->moneda->costo ?>">
            <label>Costo</label>
        </div>
        <div>
            <a onclick="btnConfirmar('<?= $_SESSION['usuario'] ?>','<?= $this->moneda->id ?>')"
               class="btn lime-600 btn-block p-x-md">Confirmar</a>
        </div>
    </div>
</div>
