<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 09/08/2017
 * Time: 09:56 AM
 */
/** @var Wallet $this */
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="table-responsive">
                <table class="table table-striped b-t b-b" width="100%">
                    <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Operacion</th>
                        <th>Compra</th>
                        <th>Pago</th>
                        <th>Precio</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?= $this->tablaTransacciones ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
