<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:56 PM
 */
?>
<style>
    img {
        width: 140px;
    }
</style>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>QR</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Bitcoin</td>
            <td>3DPcat6LLv7E5JbNSzLWdYu2CZnrogXZWD</td>
            <td><img src="https://bitso.com/getqr/3DPcat6LLv7E5JbNSzLWdYu2CZnrogXZWD/0" alt="btc"></td>
        </tr>
        <tr>
            <td>Ethereum</td>
            <td>0x29899f97c80c9e48822e7107c3a7cbb95d259aa7</td>
            <td>
                <img src="https://chart.googleapis.com/chart?chs=200x200&chld=M|1&cht=qr&chl=ethereum%3A0x29899f97c80c9e48822e7107c3a7cbb95d259aa7"
                     alt="Eth"></td>
        </tr>
        </tbody>
    </table>
</div>
</div>
