<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:43 PM
 */
?>
<div class="col-lg-4 col-xs-12">
    <table class="table">
        <tbody>
        <tr>
            <td>Balance</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Bitcoin</th>
                        <th>Ethereum</th>
                        <th>Pesos</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $controller->balance->btc_balance ?>
                        <td><?= $controller->balance->eth_balance ?>
                        <td><?= $controller->balance->mxn_balance ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>Pesos</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Bitcoin</th>
                        <th>Ethereum</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $controller->mxn_btc ?></td>
                        <td><?= $controller->mxn_eth ?></td>
                    </tr>
                    <tr>
                        <td><?= round($controller->ticker->btc_mxn->ask * Config::$plusFee, 2) ?></td>
                        <td><?= round($controller->ticker->eth_mxn->ask * Config::$plusFee, 2) ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>Bitcoin</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Pesos</th>
                        <th>Ethereum</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $controller->btc_mxn ?></td>
                        <td><?= $controller->btc_eth ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>Ethereum</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Pesos</th>
                        <th>Bitcoin</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $controller->eth_mxn ?></td>
                        <td><?= $controller->eth_btc ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>Objective</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Pesos</th>
                        <th>Bitcoin</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= Config::$objective ?></td>
                        <td><?= Config::$objectiveBitcoinFix ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>Objective</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Bid</th>
                        <th>Ask</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $controller->objectiveBid ?></td>
                        <td><?= $controller->objectiveAsk ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td>Total</td>
            <td>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Bitcoin</th>
                        <th>Ethereum</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $controller->totalBtc ?></td>
                        <td><?= $controller->totalEth ?></td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
</div>