<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:22 PM
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <!-- x/60=t 900/60=15min -->
    <meta http-equiv="refresh" content="900">
    <link rel="icon" type="image/png" href="assets/img/icon.png"/>
    <link rel="manifest" href="assets/config/manifest.json">
    <title>Bitcoin Wallet</title>
    <script src="assets/plugins/jquery/jquery-3.1.1.min.js"></script>
    <script src="assets/js/scripts.js"></script>
</head>
<body>
<?= $pagecontent ?>
</body>
</html>
