<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:56 PM
 */
?>
<div class="col-lg-4">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Type</th>
            <th>Bitcoin</th>
            <th>Peso</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Buy</td>
            <td><?= $controller->sellBtc ?></td>
            <td><?= $controller->sellMxnFee ?></td>
            <td><?= $controller->priceBtc ?></td>
            <td>
                <?= $controller->btnBuy ?>
            </td>
        </tr>
        <tr>
            <td>Sell</td>
            <td><?= $controller->sellMxn ?></td>
            <td><?= $controller->sellBtcFee ?></td>
            <td><?= $controller->priceMxn ?></td>
            <td>
                <?= $controller->btnSell ?>
            </td>
        </tr>
        </tbody>
    </table>
