<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:56 PM
 */
?>
<div class="col-lg-4 col-xs-12">
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Type</th>
                <th>Bitcoin</th>
                <th>Peso</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Buy</td>
                <td><?= $controller->sellBtc ?></td>
                <td><?= $controller->sellMxnFee ?></td>
                <td><?= $controller->priceBtc ?></td>
                <td>
                    <?= $controller->btnBuy ?>
                </td>
            </tr>
            <tr>
                <td>Sell</td>
                <td><?= $controller->sellMxn ?></td>
                <td><?= $controller->sellBtcFee ?></td>
                <td><?= $controller->priceMxn ?></td>
                <td>
                    <?= $controller->btnSell ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Type</th>
                <th>Ethereum</th>
                <th>Peso</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Buy</td>
                <td><?= $controller->sellEth ?></td>
                <td><?= $controller->sellEthMxnFee ?></td>
                <td><?= $controller->priceEth ?></td>
                <td>
                    <?= $controller->btnBuyEth ?>
                </td>
            </tr>
            <tr>
                <td>Sell</td>
                <td><?= $controller->sellEthMxn ?></td>
                <td><?= $controller->sellEthFee ?></td>
                <td><?= $controller->priceEthMxn ?></td>
                <td>
                    <?= $controller->btnSellEth ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>