<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:56 PM
 */
?>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td><input class="form-control" type="text" placeholder="BTC" onkeyup="changeBits($(this).val(),'btc')">
            </td>
            <td><span id="resAsk" title=""></span></td>
            <td>Ask: <span id="ask"
                           title="<?= $controller->ticker->btc_mxn->ask ?>"><?= round($controller->ticker->btc_mxn->ask * Config::$plusFee, 2) ?></span>
            </td>
            <td>High: <span id="high"
                            title="<?= $controller->ticker->btc_mxn->high ?>"><?= round($controller->ticker->btc_mxn->high * Config::$plusFee, 2) ?></span>
            </td>
        </tr>
        <tr>
            <td><input class="form-control" type="text" placeholder="MXN" onkeyup="changeBits($(this).val(),'mxn')">
            </td>
            <td><span id="resBid"></span></td>
            <td>Bid: <span id="bid"
                           title="<?= $controller->ticker->btc_mxn->bid ?>"><?= round($controller->ticker->btc_mxn->bid * Config::$minusFee,2) ?></span>
            </td>
            <td>Low: <span id="low"
                           title="<?= $controller->ticker->btc_mxn->low ?>"><?= round($controller->ticker->btc_mxn->low * Config::$minusFee, 2) ?></span>
            </td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td>Last: <?= $controller->ticker->btc_mxn->last ?></td>
            <td>Vwap: <?= round($controller->ticker->btc_mxn->vwap, 2) ?></td>
        </tr>
        </tbody>
    </table>
</div>
</div>
