<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:56 PM
 */
?>
<div class="col-lg-4">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Date</th>
            <th>Bitcoin</th>
            <th>Pesos</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <?= $controller->transactions ?>
        </tr>
        </tbody>
    </table>
</div>