<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 28/feb/2017
 * Time: 05:58 PM
 */
$btnGuardar = $data == null ? "btnGuardar()" : "btnEditar()";
?>
<input type="hidden" name="idPerfil" value="<?= $data->idPerfil ?>">
<div class="padding">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="box">
                <div class="box-body">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <label for="txtNombre" class="col-md-2 form-control-label">Nombre:</label>
                        <div class="col-md-6">
                            <input value="<?= $data->nombrePerfil ?>" id="txtNombre" name="nombre" type="text"
                                   class="form-control" placeholder="Nombre">
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                    <div class="form-group row">
                        <div class="dd nestable">
                            <?= $this->arbolPermisos ?>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3 submit">
                            <a onclick="navegar('perfiles')" class="btn btn-danger col-md-5">Regresar</a>
                            <a onclick="<?= $btnGuardar ?>" class="btn btn-primary col-md-5">Guardar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



