<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 27/abr/2017
 * Time: 10:26 AM
 */
/** @var Login $data */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        a:visited {
            color: #c9c9c9;
        }

        a, .s {
            color: #ffffff;
        }
    </style>
</head>
<body>
<div>
    <div style="text-align: center;">
        <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%"
               id="m_7616127435186827345m_-332101831817536392bodyTable">
            <tbody>
            <tr>
                <td align="center" valign="top" id="m_7616127435186827345m_-332101831817536392bodyCell">
                    <span style="color:#ffffff;display:none;font-size:0px;height:0px;width:0px"><?= $data->title ?></span>
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                        <tr>
                            <td align="center" bgcolor="#838e9c" valign="top"
                                id="m_7616127435186827345m_-332101831817536392templateHeader"
                                style="background-color:#838e9c;padding-right:30px;padding-left:30px">
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%"
                                       style="max-width:400px"
                                       class="m_7616127435186827345m_-332101831817536392emailContainer">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top"
                                            id="m_7616127435186827345m_-332101831817536392logoContainer"
                                            style="padding-top:40px;padding-bottom:20px">
                                            <img alt="Cbiz Money"
                                                 src="http://cbiz.mx/money/recursos/img/logo.png"
                                                 height="63" width="60"
                                                 style="color:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center" valign="top" style="padding-bottom:10px">
                                            <h1 style="color:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:30px;font-style:normal;font-weight:600;line-height:42px;letter-spacing:normal;margin:0;padding:0;text-align:center"><?= $data->title ?></h1>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center" valign="top" style="padding-bottom:40px">
                                            <p style="color:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:center"><?= $data->message ?></p>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>

                            </td>
                        </tr>
                        <tr>
                            <td align="center" bgcolor="#838e9c" valign="top"
                                id="m_7616127435186827345m_-332101831817536392headerContainer"
                                style="background-color:#838e9c;padding-right:30px;padding-left:30px">
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top">

                                            <table align="center" border="0" cellpadding="0" cellspacing="0"
                                                   width="100%" style="max-width:640px"
                                                   class="m_7616127435186827345m_-332101831817536392emailContainer">
                                                <tbody>
                                                <tr>
                                                    <td align="center" valign="top">
                                                        <table align="center" bgcolor="#FFFFFF" border="0"
                                                               cellpadding="0" cellspacing="0" width="100%"
                                                               id="m_7616127435186827345m_-332101831817536392headerTable"
                                                               style="background-color:#ffffff;border-collapse:separate;border-top-left-radius:4px;border-top-right-radius:4px">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top" width="100%"
                                                                    style="padding-top:40px;padding-bottom:0">&nbsp;
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="top" id="m_7616127435186827345m_-332101831817536392templateBody">
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top">

                                            <table align="center" border="0" cellpadding="0" cellspacing="0"
                                                   width="100%" style="max-width:700px"
                                                   class="m_7616127435186827345m_-332101831817536392emailContainer">
                                                <tbody>
                                                <tr>
                                                    <td align="right" valign="top" width="30"
                                                        class="m_7616127435186827345m_-332101831817536392mobileHide">
                                                        <img src="https://ci4.googleusercontent.com/proxy/L5tUh1OMjnXZ7pML9wTqD_Lpb0aqOQtEIxQdlBZbzz44clEn-1MlZdakDu17kOGBQjhw0qROA1em_M8TlKw1efwKeQyVgVfiWnCSel6n2HkLGJvN_NbbMg=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/tr_email/arrow.jpg"
                                                             width="30" style="display:block">
                                                    </td>
                                                    <td valign="top" width="100%"
                                                        style="padding-right:70px;padding-left:40px"
                                                        id="m_7616127435186827345m_-332101831817536392bodyContainer">
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               width="100%">
                                                            <tbody>
                                                            <tr>
                                                                <td align="left" valign="top"
                                                                    id="m_7616127435186827345m_-332101831817536392bodyContent">
                                                                    <table align="center" border="0" cellpadding="0"
                                                                           cellspacing="0" width="100%">
                                                                        <tbody>
                                                                        <tr>
                                                                            <?= $data->part_one ?>
                                                                        </tr>
                                                                        <tr>
                                                                            <?= $data->part_two ?>
                                                                        </tr>
                                                                        <tr>
                                                                            <?= $data->part_three ?>
                                                                        </tr>
                                                                        <tr>
                                                                            <?= $data->part_four ?>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td align="center" style="padding-bottom:60px"
                                                                    valign="top">
                                                                    <table align="center" border="0" cellpadding="0"
                                                                           cellspacing="0" width="100%">
                                                                        <tbody>
                                                                        <tr>
                                                                            <td align="center" valign="middle">
                                                                                <a href="http://www.cbiz.mx/money/"
                                                                                   style="background-color:#c0ca33;border-collapse:separate;border: 20px solid #c0ca33;border-right-width: 40px;border-left-width: 40px;border-radius:3px;color:#ffffff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:600;letter-spacing:.3px;text-decoration:none"
                                                                                   target="_blank">Empezar</a>
                                                                            </td>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-bottom:60px">
                                                                    <table align="center" bgcolor="#F2F2F2" border="0"
                                                                           cellpadding="0" cellspacing="0" width="100%"
                                                                           style="background-color:#f2f2f2;border-collapse:separate;border-radius:4px">
                                                                        <tbody>
                                                                        <tr>
                                                                            <?= $data->help ?>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="top"
                                id="m_7616127435186827345m_-332101831817536392templateFooter"
                                style="padding-right:30px;padding-left:30px">

                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%"
                                       style="max-width:640px"
                                       class="m_7616127435186827345m_-332101831817536392emailContainer">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top">
                                            <table align="center" border="0" cellpadding="0" cellspacing="0"
                                                   style="border-collapse:collapse">
                                                <tbody>
                                                <tr>
                                                    <td align="center" valign="top" style="padding-bottom:20px">
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               style="display:inline;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-right:20px;padding-bottom:10px">
                                                                    <a href="https://www.facebook.com/GrupoCamrey/"
                                                                       target="_blank"
                                                                       data-saferedirecturl="https://www.facebook.com/GrupoCamrey/"><img
                                                                                src="http://www.cbiz.mx/money/recursos/img/color-facebook-96.png"
                                                                                alt="Facebook" width="48"
                                                                                style="border:0;display:block;height:auto;max-width:48px;outline:none;text-decoration:none;width:48px"></a>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td valign="top" id="m_7616127435186827345m_-332101831817536392footerContent"
                                            style="color:#b7b7b7;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;line-height:24px;padding-bottom:20px;text-align:center">
                                            <p style="color:#b7b7b7;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:center">
                                                &copy; <?= date('Y') ?> Cbiz Money<sup>&reg;</sup>, All Rights Reserved.<br>Juan
                                                Alonso de Torres #202 Piso 3 San Jer&oacute;nimo. Le&oacute;n Gto.</p>
                                            <a href="http://www.cbiz.mx/"
                                               style="color:#b7b7b7;text-decoration:underline"
                                               class="m_7616127435186827345m_-332101831817536392utilityLink"
                                               target="_blank"
                                               data-saferedirecturl="http://www.cbiz.mx/">Contact
                                                Us</a><span
                                                    class="m_7616127435186827345m_-332101831817536392mobileHide"> &nbsp; &bull; &nbsp; </span><a
                                                    href=""
                                                    style="color:#b7b7b7;text-decoration:underline"
                                                    class="m_7616127435186827345m_-332101831817536392utilityLink"
                                                    target="_blank"
                                                    data-saferedirecturl="">Terms
                                                of Use</a><span
                                                    class="m_7616127435186827345m_-332101831817536392mobileHide"> &nbsp; &bull; &nbsp; </span><a
                                                    href=""
                                                    style="color:#b7b7b7;text-decoration:underline"
                                                    class="m_7616127435186827345m_-332101831817536392utilityLink"
                                                    target="_blank"
                                                    data-saferedirecturl="">Privacy
                                                Policy</a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <img src="https://ci4.googleusercontent.com/proxy/-Yg0RqYWn2VpwgVlYqGHwNbS4i07iOPS3yrhGOoxrgnTiMUloQxYczBHxfcEUa1mWF7mexqb-zlui7IsXY9fFwS0TCcmQjm7lCjX5dYXuZ5hJRCXFEceC3UWcIIF5F08mlxr-_aHthD_r7y-KJhnmfA=s0-d-e1-ft#http://click.mailchimpapp.com/track/open.php?u=10612303&amp;id=59ecf27af38f4f9c86ac52d255970f5c"
         height="1" width="1">
</div>
</body>
</html>
