<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <div style="text-align: center;">
        <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%"
               id="m_7616127435186827345m_-332101831817536392bodyTable">
            <tbody>
            <tr>
                <td align="center" valign="top" id="m_7616127435186827345m_-332101831817536392bodyCell">
                    <span style="color:#ffffff;display:none;font-size:0px;height:0px;width:0px">Thank you for joining MailChimp, Luis! Here are some tips to get you started.</span>

                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                        <tr>
                            <td align="center" bgcolor="#52BAD5" valign="top"
                                id="m_7616127435186827345m_-332101831817536392templateHeader"
                                style="background-color:#52bad5;padding-right:30px;padding-left:30px">

                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%"
                                       style="max-width:400px"
                                       class="m_7616127435186827345m_-332101831817536392emailContainer">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top"
                                            id="m_7616127435186827345m_-332101831817536392logoContainer"
                                            style="padding-top:40px;padding-bottom:20px">
                                            <img alt="MailChimp"
                                                 src="https://ci6.googleusercontent.com/proxy/zzcT-riDenHH1k2MzDa8koFcow2PL1gar8Dto2ciGNptO6hOTuwX3rrwpwUyy4UEI7DtnfK3R8wTooh-H0wEPGHbSK0WBaw3u7Xc2veufCdDjyq3ndggUMK88xo=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/icons/wink_freddie.png"
                                                 height="63" width="60"
                                                 style="color:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center" valign="top" style="padding-bottom:10px">
                                            <h1 style="color:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:30px;font-style:normal;font-weight:600;line-height:42px;letter-spacing:normal;margin:0;padding:0;text-align:center">
                                                Welcome to MailChimp!</h1>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center" valign="top" style="padding-bottom:40px">
                                            <p style="color:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:center">
                                                Thank you for joining us, Luis. Here's an overview of how your MailChimp
                                                account works.</p>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>

                            </td>
                        </tr>
                        <tr>
                            <td align="center" bgcolor="#52BAD5" valign="top"
                                id="m_7616127435186827345m_-332101831817536392headerContainer"
                                style="background-color:#52bad5;padding-right:30px;padding-left:30px">
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top">

                                            <table align="center" border="0" cellpadding="0" cellspacing="0"
                                                   width="100%" style="max-width:640px"
                                                   class="m_7616127435186827345m_-332101831817536392emailContainer">
                                                <tbody>
                                                <tr>
                                                    <td align="center" valign="top">
                                                        <table align="center" bgcolor="#FFFFFF" border="0"
                                                               cellpadding="0" cellspacing="0" width="100%"
                                                               id="m_7616127435186827345m_-332101831817536392headerTable"
                                                               style="background-color:#ffffff;border-collapse:separate;border-top-left-radius:4px;border-top-right-radius:4px">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top" width="100%"
                                                                    style="padding-top:40px;padding-bottom:0">&nbsp;
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>

                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="top" id="m_7616127435186827345m_-332101831817536392templateBody">
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top">

                                            <table align="center" border="0" cellpadding="0" cellspacing="0"
                                                   width="100%" style="max-width:700px"
                                                   class="m_7616127435186827345m_-332101831817536392emailContainer">
                                                <tbody>
                                                <tr>
                                                    <td align="right" valign="top" width="30"
                                                        class="m_7616127435186827345m_-332101831817536392mobileHide">
                                                        <img src="https://ci4.googleusercontent.com/proxy/L5tUh1OMjnXZ7pML9wTqD_Lpb0aqOQtEIxQdlBZbzz44clEn-1MlZdakDu17kOGBQjhw0qROA1em_M8TlKw1efwKeQyVgVfiWnCSel6n2HkLGJvN_NbbMg=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/tr_email/arrow.jpg"
                                                             width="30" style="display:block">
                                                    </td>
                                                    <td valign="top" width="100%"
                                                        style="padding-right:70px;padding-left:40px"
                                                        id="m_7616127435186827345m_-332101831817536392bodyContainer">
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               width="100%">
                                                            <tbody>
                                                            <tr>
                                                                <td align="left" valign="top"
                                                                    id="m_7616127435186827345m_-332101831817536392bodyContent">
                                                                    <table align="center" border="0" cellpadding="0"
                                                                           cellspacing="0" width="100%">
                                                                        <tbody>
                                                                        <tr>
                                                                            <td align="left" valign="top"
                                                                                style="padding-right:20px;padding-bottom:60px">
                                                                                <img alt="Lists"
                                                                                     src="https://ci5.googleusercontent.com/proxy/4dgReKEGZnmZ7rJ8k4pSlgFC0zWPtnBUlg0L8pACkFlz3SRqWuewJLXWqvxE9coStbAR27QnHcY8yukF8pk_MJ8VV-cXMIbl1WtxHOyoeOuSrrJRZe0UtCA=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/icons/list_icon.png"
                                                                                     width="48"
                                                                                     style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:600;height:auto;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                                                            </td>
                                                                            <td align="left" valign="top"
                                                                                style="padding-bottom:40px">


                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Build Your List</p>
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:left">
                                                                                    Your subscribers are <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoid0tWUm05a3N2Yzdiek1GeG11b2czSW93NmlBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9saXN0c1xcXC9ncm93dGhcXFwvZ2V0dGluZy1zdGFydGVkLXdpdGgtbGlzdHM_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjI2ZDBhYTY4NTM0MDYxNmNjOWU4YzE2NjgxZjcwN2IxODMwODM0NjBcIl19In0"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoid0tWUm05a3N2Yzdiek1GeG11b2czSW93NmlBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9saXN0c1xcXC9ncm93dGhcXFwvZ2V0dGluZy1zdGFydGVkLXdpdGgtbGlzdHM_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjI2ZDBhYTY4NTM0MDYxNmNjOWU4YzE2NjgxZjcwN2IxODMwODM0NjBcIl19In0&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNFQ02h23-Meu8mQYg_gPPvCfCpuVA">managed
                                                                                    in lists</a>. Check out our <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiSGVOaTMxUGowdk83WGdicG1kSGM0RHJNS1RJIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9hY2NvdW50c1xcXC9jb21wbGlhbmNlLXRpcHNcXFwvZ3VpZGVsaW5lcy1mb3ItbGlzdC1jb21wbGlhbmNlP3V0bV9zb3VyY2U9bWFpbGNoaW1wLWFwcCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jb250ZW50PXNpZ251cC13ZWxjb21lJnV0bV9jYW1wYWlnbj1vbmJvYXJkaW5nXCIsXCJpZFwiOlwiNTllY2YyN2FmMzhmNGY5Yzg2YWM1MmQyNTU5NzBmNWNcIixcInVybF9pZHNcIjpbXCIzYzQ0NTEzYjk2MWU3ODZmNTRlODI5MThjZmQzZWY1ZGIyOTRkMjRkXCJdfSJ9"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiSGVOaTMxUGowdk83WGdicG1kSGM0RHJNS1RJIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9hY2NvdW50c1xcXC9jb21wbGlhbmNlLXRpcHNcXFwvZ3VpZGVsaW5lcy1mb3ItbGlzdC1jb21wbGlhbmNlP3V0bV9zb3VyY2U9bWFpbGNoaW1wLWFwcCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jb250ZW50PXNpZ251cC13ZWxjb21lJnV0bV9jYW1wYWlnbj1vbmJvYXJkaW5nXCIsXCJpZFwiOlwiNTllY2YyN2FmMzhmNGY5Yzg2YWM1MmQyNTU5NzBmNWNcIixcInVybF9pZHNcIjpbXCIzYzQ0NTEzYjk2MWU3ODZmNTRlODI5MThjZmQzZWY1ZGIyOTRkMjRkXCJdfSJ9&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNHHJR3MKtB7U7X70sbJiI8H0Jm0jQ">list
                                                                                    requirements</a> and then learn how
                                                                                    to grow a list of subscribers.</p>

                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td align="left" valign="top"
                                                                                style="padding-right:20px;padding-bottom:60px">
                                                                                <img alt="Email"
                                                                                     src="https://ci5.googleusercontent.com/proxy/WD-sqoYz7-lPJmHxfrzvM4_niocfWcydIsq9cpVt3COAMww7ilJe3mEk30lW5abxBysTo6mu4a2PhcmvA6Oqj_OAef7wekz4fAqWz8Sz_Abuk4JADt0rFQ06W8COaw=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/icons/campaigns_icon.png"
                                                                                     width="48"
                                                                                     style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:600;height:auto;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                                                            </td>
                                                                            <td align="left" valign="top"
                                                                                style="padding-bottom:40px">
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Create a Campaign</p>
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:left">
                                                                                    Jump start your <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiWU5BVjlKZDdySnpVTkppU0prU3FRU25feUVBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvZGVzaWduXFxcL2Rlc2lnbi1mb3ItZW1haWw_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjM3YzQ1YmRkYjAxNDFkNzcxZThhZjI3YTAzOGYwMGY0N2VhMzUyZTRcIl19In0"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiWU5BVjlKZDdySnpVTkppU0prU3FRU25feUVBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvZGVzaWduXFxcL2Rlc2lnbi1mb3ItZW1haWw_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjM3YzQ1YmRkYjAxNDFkNzcxZThhZjI3YTAzOGYwMGY0N2VhMzUyZTRcIl19In0&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNEpwye_BWeJFPoOBYPk_2YKezV-GQ">email
                                                                                    design</a> knowledge and <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiSFB3M2lMVk5tR3RJb0htM0ZmeDBTODlNTzNvIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvd2F5cy10by1idWlsZFxcXC9jcmVhdGUtYS1jYW1wYWlnbi13aXRoLWNhbXBhaWduLWJ1aWxkZXI_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjM1ZjZlYTU2OTUxMDM5OWNkY2EwM2I1MDE1NzE4Yzc2NjIyZDA1NGFcIl19In0"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiSFB3M2lMVk5tR3RJb0htM0ZmeDBTODlNTzNvIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvd2F5cy10by1idWlsZFxcXC9jcmVhdGUtYS1jYW1wYWlnbi13aXRoLWNhbXBhaWduLWJ1aWxkZXI_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjM1ZjZlYTU2OTUxMDM5OWNkY2EwM2I1MDE1NzE4Yzc2NjIyZDA1NGFcIl19In0&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNE3K_yhhm_sfMaO9OJby90e3b9ghA">build
                                                                                    your campaign</a> to share your
                                                                                    message with your subscribers.</p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td align="left" valign="top"
                                                                                style="padding-right:20px;padding-bottom:60px">
                                                                                <img alt="Test"
                                                                                     src="https://ci4.googleusercontent.com/proxy/Jlstza95JXEZ-XLU84hu8t2l_7VEQWe2DcXHw-yoROHkJzLiiAri_Ki-z75Qm3MB530G8JfsosIowNvzLen-2ITrPEgm6W5LLvKBnLTO14SJBVPUpL9jQ0g=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/icons/test_icon.png"
                                                                                     width="48"
                                                                                     style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:600;height:auto;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                                                            </td>
                                                                            <td align="left" valign="top"
                                                                                style="padding-bottom:40px">
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Test and Send</p>
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:left">
                                                                                    <a href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiZWdiUjgtQ2FrRVRCZ1JnUU1IRWlBSUMzWnJVIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvcHJldmlld3MtYW5kLXRlc3RzXFxcL2VtYWlsLWNhbXBhaWduLXRlc3RpbmctdGlwcz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiNDNhMmYwOTY5YjQwZjMxYzJiMGZmMzg0MDhkYTdjOTE5NDE0ZmZlNVwiXX0ifQ"
                                                                                       style="color:#6dc6dd;text-decoration:underline"
                                                                                       target="_blank"
                                                                                       data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiZWdiUjgtQ2FrRVRCZ1JnUU1IRWlBSUMzWnJVIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvcHJldmlld3MtYW5kLXRlc3RzXFxcL2VtYWlsLWNhbXBhaWduLXRlc3RpbmctdGlwcz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiNDNhMmYwOTY5YjQwZjMxYzJiMGZmMzg0MDhkYTdjOTE5NDE0ZmZlNVwiXX0ifQ&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNGwq0p_vy59VSjFqKqkksC14wGg_g">Test
                                                                                        your campaign</a> to get an idea
                                                                                    of what your subscribers will see in
                                                                                    their inboxes. When you're ready, <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoid0ZkWmlHUHYyMC1xQ25Ub0p3RkZIWmxGUmRvIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvY29uZmlybWF0aW9uLWFuZC1zZW5kaW5nXFxcL3NjaGVkdWxlLXBhdXNlLW9yLXNlbmQtYS1jYW1wYWlnbj91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiNzMyNzQzMTU0NDkwZDQ0NzI5YjFjOTI1MjU5NzI2MDJlYTRiNzEwYlwiXX0ifQ"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoid0ZkWmlHUHYyMC1xQ25Ub0p3RkZIWmxGUmRvIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9jYW1wYWlnbnNcXFwvY29uZmlybWF0aW9uLWFuZC1zZW5kaW5nXFxcL3NjaGVkdWxlLXBhdXNlLW9yLXNlbmQtYS1jYW1wYWlnbj91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiNzMyNzQzMTU0NDkwZDQ0NzI5YjFjOTI1MjU5NzI2MDJlYTRiNzEwYlwiXX0ifQ&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNEP7HX06UupXxVZ2-I8K2fRD5OOiw">schedule
                                                                                    or send</a> your campaign.</p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td align="left" valign="top"
                                                                                style="padding-right:20px;padding-bottom:60px">
                                                                                <img alt="Reports"
                                                                                     src="https://ci4.googleusercontent.com/proxy/1zrPTi3qiwXJHx8dYPvpy0XmfwBXde5p0JY7059ESNPgU3iZHrvg-v1MMZ3-21at6Lto9VqVbVfn_XjwhYBiM4MO2ncW74yfckOZ8wRrA1kip3cBNMy0Mry0eA=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/icons/report_icon.png"
                                                                                     width="48"
                                                                                     style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:600;height:auto;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                                                            </td>
                                                                            <td align="left" valign="top"
                                                                                style="padding-bottom:40px">
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Run Reports</p>
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:left">
                                                                                    Check out campaign performance in <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiRGtpNU5sd2c0Z3h3Y0l0TTVHaE12TDdsTEI4IiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9yZXBvcnRzXFxcL2Fib3V0LWNhbXBhaWduLXJlcG9ydHM_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjQ1MzFkZjE3YzdmNjYxOTIwYzc4NDY4Zjc1NDJjNTc0MGVhMGU3YjNcIl19In0"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiRGtpNU5sd2c0Z3h3Y0l0TTVHaE12TDdsTEI4IiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9yZXBvcnRzXFxcL2Fib3V0LWNhbXBhaWduLXJlcG9ydHM_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjQ1MzFkZjE3YzdmNjYxOTIwYzc4NDY4Zjc1NDJjNTc0MGVhMGU3YjNcIl19In0&amp;source=gmail&amp;ust=1492817404665000&amp;usg=AFQjCNGOwShS5sOdZWLSjPF5wYzGCdZRyA">reports</a>.
                                                                                    Improve your strategy using powerful
                                                                                    analytics and data to create
                                                                                    campaigns that <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiQnFqeGlpSE4wNmx2Q2pjMHNfTS1sR3Z6T2lZIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9zZWdtZW50c1xcXC9nZXR0aW5nLXN0YXJ0ZWQtd2l0aC1zZWdtZW50cz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiYmY0ZGE2ZTAzODdjYzcwYWJkOGVmMTNjYjJkNzI1MjMxZjJmY2EwNlwiXX0ifQ"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiQnFqeGlpSE4wNmx2Q2pjMHNfTS1sR3Z6T2lZIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9zZWdtZW50c1xcXC9nZXR0aW5nLXN0YXJ0ZWQtd2l0aC1zZWdtZW50cz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiYmY0ZGE2ZTAzODdjYzcwYWJkOGVmMTNjYjJkNzI1MjMxZjJmY2EwNlwiXX0ifQ&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNGSa9hTxpOKCtijukrwNc01Orr7Kg">target
                                                                                    subscribers</a> based on their
                                                                                    interests.</p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td align="left" valign="top"
                                                                                style="padding-right:20px;padding-bottom:60px">
                                                                                <img alt="Learn"
                                                                                     src="https://ci3.googleusercontent.com/proxy/r0UiJqYb2PWQ2cur-emdeo7yDOuyr88PhbjhLlCXdXP05xtfsEAAZe56B8XGXHNg053JRzZXdNSPF97FGYEiwBOOzUFKmLOM4CybNgPpRJXZbykIgA=s0-d-e1-ft#http://cdn-images.mailchimp.com/template_images/icons/bulby.png"
                                                                                     width="48"
                                                                                     style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:600;height:auto;letter-spacing:-1px;padding:0;margin:0;text-align:center">
                                                                            </td>
                                                                            <td align="left" valign="top"
                                                                                style="padding-bottom:40px">
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Keep Improving</p>
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:left">
                                                                                    <a href="http://click.mailchimpapp.com/track/click/10612303/mailchimp.com?p=eyJzIjoiNnVVaU1ibVRTS1dLVXNza3ctWDZkVlVZTzJJIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvbWFpbGNoaW1wLmNvbVxcXC9yZXNvdXJjZXNcXFwvZ3VpZGVzXFxcL2dldHRpbmctc3RhcnRlZC13aXRoLW1haWxjaGltcFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjczNzY5YjdjYTY3ZGJkYzI1NTVjNDg0MDM1ZjZjZDFkZjNlOTgwNGJcIl19In0"
                                                                                       style="color:#6dc6dd;text-decoration:underline"
                                                                                       target="_blank"
                                                                                       data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/mailchimp.com?p%3DeyJzIjoiNnVVaU1ibVRTS1dLVXNza3ctWDZkVlVZTzJJIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvbWFpbGNoaW1wLmNvbVxcXC9yZXNvdXJjZXNcXFwvZ3VpZGVzXFxcL2dldHRpbmctc3RhcnRlZC13aXRoLW1haWxjaGltcFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjczNzY5YjdjYTY3ZGJkYzI1NTVjNDg0MDM1ZjZjZDFkZjNlOTgwNGJcIl19In0&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNFfk9usFXoSNMXryXIWTMQlLKkiRw">Getting
                                                                                        Started</a> and <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoidU1qSlZyYWtncW85NXNaV21DU1d0YzBrcXBRIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9hY2NvdW50c1xcXC9hY2NvdW50LXNldHVwXFxcL21haWxjaGltcC1mdW5kYW1lbnRhbHM_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjliMjQwY2UwMDMzYmQyNWY2NTc1MTkxZjM0MTBjNDFiYjgzYTMxN2JcIl19In0"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoidU1qSlZyYWtncW85NXNaV21DU1d0YzBrcXBRIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC9hY2NvdW50c1xcXC9hY2NvdW50LXNldHVwXFxcL21haWxjaGltcC1mdW5kYW1lbnRhbHM_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjliMjQwY2UwMDMzYmQyNWY2NTc1MTkxZjM0MTBjNDFiYjgzYTMxN2JcIl19In0&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNElNTZgjwVN3BKl5GuynU8cw3F_Jw">MailChimp
                                                                                    Fundamentals</a> help outline the
                                                                                    basics of your account, and our
                                                                                    comprehensive <a
                                                                                        href="http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p=eyJzIjoiSU1vQ2lVQlZ6VWNNM1JLbTE5eEd4V0VpOGJjIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjBmOTQ4MmFhNTkyMDg4ZGQyNGNkMDFlZjA1NzE5NzkyOTdlMmM3NWNcIl19In0"
                                                                                        style="color:#6dc6dd;text-decoration:underline"
                                                                                        target="_blank"
                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/kb.mailchimp.com?p%3DeyJzIjoiSU1vQ2lVQlZ6VWNNM1JLbTE5eEd4V0VpOGJjIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwva2IubWFpbGNoaW1wLmNvbVxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjBmOTQ4MmFhNTkyMDg4ZGQyNGNkMDFlZjA1NzE5NzkyOTdlMmM3NWNcIl19In0&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNHoElkYtVgnuP_hmkIJo2xRmODo8g">Knowledge
                                                                                    Base</a> is there when you have
                                                                                    questions.</p>
                                                                            </td>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td align="center" style="padding-bottom:60px"
                                                                    valign="top">
                                                                    <table align="center" border="0" cellpadding="0"
                                                                           cellspacing="0" width="100%">
                                                                        <tbody>
                                                                        <tr>
                                                                            <td align="center" valign="middle">

                                                                                <a href="http://click.mailchimpapp.com/track/click/10612303/login.mailchimp.com?p=eyJzIjoiY3BKc01USGdLeTBsbFkwOHNJSzQyem5IZ2FJIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2xvZ2luLm1haWxjaGltcC5jb21cXFwvP3V0bV9zb3VyY2U9bWFpbGNoaW1wLWFwcCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jb250ZW50PXNpZ251cC13ZWxjb21lJnV0bV9jYW1wYWlnbj1vbmJvYXJkaW5nXCIsXCJpZFwiOlwiNTllY2YyN2FmMzhmNGY5Yzg2YWM1MmQyNTU5NzBmNWNcIixcInVybF9pZHNcIjpbXCI1NDQyZTdkZDc0MzE5N2I1YzI2ZTEzZjZjMGQyZTk1Mzg5ZjkwNmZiXCJdfSJ9"
                                                                                   style="background-color:#6dc6dd;border-collapse:separate;border-top:20px solid #6dc6dd;border-right:40px solid #6dc6dd;border-bottom:20px solid #6dc6dd;border-left:40px solid #6dc6dd;border-radius:3px;color:#ffffff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:600;letter-spacing:.3px;text-decoration:none"
                                                                                   target="_blank"
                                                                                   data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/login.mailchimp.com?p%3DeyJzIjoiY3BKc01USGdLeTBsbFkwOHNJSzQyem5IZ2FJIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2xvZ2luLm1haWxjaGltcC5jb21cXFwvP3V0bV9zb3VyY2U9bWFpbGNoaW1wLWFwcCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jb250ZW50PXNpZ251cC13ZWxjb21lJnV0bV9jYW1wYWlnbj1vbmJvYXJkaW5nXCIsXCJpZFwiOlwiNTllY2YyN2FmMzhmNGY5Yzg2YWM1MmQyNTU5NzBmNWNcIixcInVybF9pZHNcIjpbXCI1NDQyZTdkZDc0MzE5N2I1YzI2ZTEzZjZjMGQyZTk1Mzg5ZjkwNmZiXCJdfSJ9&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNE9GpLhsfI8uNF6OFOutgJutXYNug">Get
                                                                                    Started</a>

                                                                            </td>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-bottom:60px">
                                                                    <table align="center" bgcolor="#F2F2F2" border="0"
                                                                           cellpadding="0" cellspacing="0" width="100%"
                                                                           style="background-color:#f2f2f2;border-collapse:separate;border-radius:4px">
                                                                        <tbody>
                                                                        <tr>
                                                                            <td align="center" valign="middle"
                                                                                style="padding:20px">
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Need Additional Support?</p>
                                                                                <p style="color:#737373;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:24px;padding-top:0;margin-top:0;text-align:left">
                                                                                    Free accounts come with 30 days of
                                                                                    email support, and all paid accounts
                                                                                    have access to email and live chat
                                                                                    support.</p>
                                                                            </td>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>

                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="top"
                                id="m_7616127435186827345m_-332101831817536392templateFooter"
                                style="padding-right:30px;padding-left:30px">

                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%"
                                       style="max-width:640px"
                                       class="m_7616127435186827345m_-332101831817536392emailContainer">
                                    <tbody>
                                    <tr>
                                        <td align="center" valign="top">
                                            <table align="center" border="0" cellpadding="0" cellspacing="0"
                                                   style="border-collapse:collapse">
                                                <tbody>
                                                <tr>
                                                    <td align="center" valign="top" style="padding-bottom:20px">

                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               style="display:inline;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-right:20px;padding-bottom:10px">
                                                                    <a href="http://click.mailchimpapp.com/track/click/10612303/www.facebook.com?p=eyJzIjoiSTFXWGhfbEVCbGNaNnBINTBXcV9PUnh5RmVZIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5mYWNlYm9vay5jb21cXFwvbWFpbGNoaW1wXFxcLz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiMGEyMDJjYzgzMTllOGFiYzJmYmQyMTE0OTE5YjdlN2Q4NDQ5N2Y3NFwiXX0ifQ"
                                                                       target="_blank"
                                                                       data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/www.facebook.com?p%3DeyJzIjoiSTFXWGhfbEVCbGNaNnBINTBXcV9PUnh5RmVZIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5mYWNlYm9vay5jb21cXFwvbWFpbGNoaW1wXFxcLz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiMGEyMDJjYzgzMTllOGFiYzJmYmQyMTE0OTE5YjdlN2Q4NDQ5N2Y3NFwiXX0ifQ&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNF0kTCRltKMvH0O7rN3_ltSxFED_w"><img
                                                                            src="https://ci3.googleusercontent.com/proxy/-7SB8g4t1ptk1UP3zU8tajybT6Io3yqnVPDZ_OnGVFc0RiasRoK808PVxtvdW-Ui5KVRehXq7sXVMplihB-KCaxVOET5EDXFIehibYjn4vDh0Rd54NOxT9trToTBzq8h6OU=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-facebook-96.png"
                                                                            alt="Facebook" width="48"
                                                                            style="border:0;display:block;height:auto;max-width:48px;outline:none;text-decoration:none;width:48px"></a>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>

                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               style="display:inline;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-right:20px;padding-bottom:10px">
                                                                    <a href="http://click.mailchimpapp.com/track/click/10612303/twitter.com?p=eyJzIjoic0ZjN0Q4RXpCZ3h5ZWw5SjNYOEZ2Q3pCSGNVIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3R3aXR0ZXIuY29tXFxcL01haWxDaGltcFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjlhNzllZmIzYTk0N2NjNjc5NjkyZDlmMjYxNDhmOTE4YWY1MDQ0MjBcIl19In0"
                                                                       target="_blank"
                                                                       data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/twitter.com?p%3DeyJzIjoic0ZjN0Q4RXpCZ3h5ZWw5SjNYOEZ2Q3pCSGNVIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3R3aXR0ZXIuY29tXFxcL01haWxDaGltcFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjlhNzllZmIzYTk0N2NjNjc5NjkyZDlmMjYxNDhmOTE4YWY1MDQ0MjBcIl19In0&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNHd23B21Vj3VSWEdGEuMixeSLuPPg"><img
                                                                            src="https://ci4.googleusercontent.com/proxy/E8Ev30bGwvmg__uqkUu0u0MoEGws-vF4KFH8jSA_9Gjy1UO8uLIvYJ3XB7mT0Cdc51HF_anmkerM0yV2ERJpSnk69Xq-zHFpgEWTw3iL5fCVvjAKYVaXEnRx-jJ6tOD_KA=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-twitter-96.png"
                                                                            alt="Twitter" width="48"
                                                                            style="border:0;display:block;height:auto;max-width:48px;outline:none;text-decoration:none;width:48px"></a>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>

                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               style="display:inline;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-right:20px;padding-bottom:10px">
                                                                    <a href="http://click.mailchimpapp.com/track/click/10612303/www.instagram.com?p=eyJzIjoiMFgzMmZGWUhWRElfX2llankteUpyZy03U09RIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5pbnN0YWdyYW0uY29tXFxcL21haWxjaGltcFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjRhNTFlZTU3YWJhZjk3YTYxM2Q0ZDg2ODE4ZjI2MzU1MTQ3OWRmMDlcIl19In0"
                                                                       target="_blank"
                                                                       data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/www.instagram.com?p%3DeyJzIjoiMFgzMmZGWUhWRElfX2llankteUpyZy03U09RIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5pbnN0YWdyYW0uY29tXFxcL21haWxjaGltcFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjRhNTFlZTU3YWJhZjk3YTYxM2Q0ZDg2ODE4ZjI2MzU1MTQ3OWRmMDlcIl19In0&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNFqwosDzHiuHnGFvION43c6F_sPBg"><img
                                                                            src="https://ci3.googleusercontent.com/proxy/BZT18_Lzo_047sk7iy_n7Ws94Yj8lxS1FLnephZqAj5k69pRno_AdnA4Rl8kkS9WDdYsAZFyuaUnSnEJTQGW35br2inwvqfl7aZl4BSjN7XfWVEZIhLtw205REMrz6p5Kp6f=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-instagram-96.png"
                                                                            alt="Instagram"
                                                                            class="m_7616127435186827345m_-332101831817536392mcnFollowBlockIcon"
                                                                            width="48"
                                                                            style="border:0;display:block;height:auto;max-width:48px;outline:none;text-decoration:none;width:48px"></a>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>

                                                        <table align="left" border="0" cellpadding="0" cellspacing="0"
                                                               style="display:inline;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td align="center" valign="top"
                                                                    style="padding-right:0;padding-bottom:10px">
                                                                    <a href="http://click.mailchimpapp.com/track/click/10612303/www.linkedin.com?p=eyJzIjoiYUdlLVRvc0tJd1BPWkVZeU9haXhKTEFFaWJBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5saW5rZWRpbi5jb21cXFwvY29tcGFueVxcXC9tYWlsY2hpbXBcXFwvP3V0bV9zb3VyY2U9bWFpbGNoaW1wLWFwcCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jb250ZW50PXNpZ251cC13ZWxjb21lJnV0bV9jYW1wYWlnbj1vbmJvYXJkaW5nXCIsXCJpZFwiOlwiNTllY2YyN2FmMzhmNGY5Yzg2YWM1MmQyNTU5NzBmNWNcIixcInVybF9pZHNcIjpbXCIxYWQ1Y2U2MTUxNjVhYzllNDg3ZjIyMjhkZWI1ZGI4MzRhYzUxOWI3XCJdfSJ9"
                                                                       target="_blank"
                                                                       data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/www.linkedin.com?p%3DeyJzIjoiYUdlLVRvc0tJd1BPWkVZeU9haXhKTEFFaWJBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5saW5rZWRpbi5jb21cXFwvY29tcGFueVxcXC9tYWlsY2hpbXBcXFwvP3V0bV9zb3VyY2U9bWFpbGNoaW1wLWFwcCZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jb250ZW50PXNpZ251cC13ZWxjb21lJnV0bV9jYW1wYWlnbj1vbmJvYXJkaW5nXCIsXCJpZFwiOlwiNTllY2YyN2FmMzhmNGY5Yzg2YWM1MmQyNTU5NzBmNWNcIixcInVybF9pZHNcIjpbXCIxYWQ1Y2U2MTUxNjVhYzllNDg3ZjIyMjhkZWI1ZGI4MzRhYzUxOWI3XCJdfSJ9&amp;source=gmail&amp;ust=1492817404666000&amp;usg=AFQjCNGb8R3z6ndCUU08alHFBzJyN3IZQA"><img
                                                                            src="https://ci5.googleusercontent.com/proxy/id-DgEArKzFchuCxBUzDjvjrH_qY6MC4TdybHhzbPi2puETerHDuEcK8VDhA0wSydsxdmcL_U96y9nvONV0c1vMLklHClymKE2bB4AybbPTKHYwFv7zd1pU2i8vbmQWibqI=s0-d-e1-ft#https://cdn-images.mailchimp.com/icons/social-block-v2/color-linkedin-96.png"
                                                                            alt="LinkedIn" width="48"
                                                                            style="border:0;display:block;height:auto;max-width:48px;outline:none;text-decoration:none;width:48px"></a>
                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table>

                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td valign="top" id="m_7616127435186827345m_-332101831817536392footerContent"
                                            style="color:#b7b7b7;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;line-height:24px;padding-bottom:20px;text-align:center">
                                            <p style="color:#b7b7b7;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;line-height:24px;padding:0;margin:0;text-align:center">
                                                © 2001-2016 MailChimp<sup>®</sup>, All Rights Reserved.<br>675 Ponce De
                                                Leon Ave NE • Suite 5000 • Atlanta, GA 30308 USA</p>
                                            <a href="http://click.mailchimpapp.com/track/click/10612303/www.mailchimp.com?p=eyJzIjoieHdRNzhxMldQVGhZQ2tqd2FBbEFnNHZXSlljIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3Lm1haWxjaGltcC5jb21cXFwvY29udGFjdFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjU3ODBkMTBhZGViZmNmMzBjNmNkOTBlYTBjMDM3MzNmNWE2ZTllODdcIl19In0"
                                               style="color:#b7b7b7;text-decoration:underline"
                                               class="m_7616127435186827345m_-332101831817536392utilityLink"
                                               target="_blank"
                                               data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/www.mailchimp.com?p%3DeyJzIjoieHdRNzhxMldQVGhZQ2tqd2FBbEFnNHZXSlljIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3Lm1haWxjaGltcC5jb21cXFwvY29udGFjdFxcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcIjU3ODBkMTBhZGViZmNmMzBjNmNkOTBlYTBjMDM3MzNmNWE2ZTllODdcIl19In0&amp;source=gmail&amp;ust=1492817404667000&amp;usg=AFQjCNGz6ckhKJ3ct_rVRH5c0i-6FmXYAw">Contact
                                                Us</a><span
                                                class="m_7616127435186827345m_-332101831817536392mobileHide"> &nbsp; • &nbsp; </span><a
                                                href="http://click.mailchimpapp.com/track/click/10612303/mailchimp.com?p=eyJzIjoiMFFSdTVrRU1lWTMwbUgwSTFFaDVKdW9USGZrIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvbWFpbGNoaW1wLmNvbVxcXC9sZWdhbFxcXC90ZXJtc1xcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcImJkNzM3MTcxY2YxYThlNjgxZDYwMDg0M2Q3YzgxZDVhMjQxNDkyNTZcIl19In0"
                                                style="color:#b7b7b7;text-decoration:underline"
                                                class="m_7616127435186827345m_-332101831817536392utilityLink"
                                                target="_blank"
                                                data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/mailchimp.com?p%3DeyJzIjoiMFFSdTVrRU1lWTMwbUgwSTFFaDVKdW9USGZrIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvbWFpbGNoaW1wLmNvbVxcXC9sZWdhbFxcXC90ZXJtc1xcXC8_dXRtX3NvdXJjZT1tYWlsY2hpbXAtYXBwJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9c2lnbnVwLXdlbGNvbWUmdXRtX2NhbXBhaWduPW9uYm9hcmRpbmdcIixcImlkXCI6XCI1OWVjZjI3YWYzOGY0ZjljODZhYzUyZDI1NTk3MGY1Y1wiLFwidXJsX2lkc1wiOltcImJkNzM3MTcxY2YxYThlNjgxZDYwMDg0M2Q3YzgxZDVhMjQxNDkyNTZcIl19In0&amp;source=gmail&amp;ust=1492817404667000&amp;usg=AFQjCNG3aXeWaTs88SPs44yl6nsyIhDzjg">Terms
                                            of Use</a><span
                                                class="m_7616127435186827345m_-332101831817536392mobileHide"> &nbsp; • &nbsp; </span><a
                                                href="http://click.mailchimpapp.com/track/click/10612303/mailchimp.com?p=eyJzIjoia0tCc0d6NzhCWnJrT2s2RmpIdk1Bb2NvdmpBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvbWFpbGNoaW1wLmNvbVxcXC9sZWdhbFxcXC9wcml2YWN5XFxcLz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiZjE3ODZlNmNlYzk3NTBkMmQzMDM3YWM1M2YyN2RmMGNkZjFlOTAwNFwiXX0ifQ"
                                                style="color:#b7b7b7;text-decoration:underline"
                                                class="m_7616127435186827345m_-332101831817536392utilityLink"
                                                target="_blank"
                                                data-saferedirecturl="https://www.google.com/url?q=http://click.mailchimpapp.com/track/click/10612303/mailchimp.com?p%3DeyJzIjoia0tCc0d6NzhCWnJrT2s2RmpIdk1Bb2NvdmpBIiwidiI6MSwicCI6IntcInVcIjoxMDYxMjMwMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvbWFpbGNoaW1wLmNvbVxcXC9sZWdhbFxcXC9wcml2YWN5XFxcLz91dG1fc291cmNlPW1haWxjaGltcC1hcHAmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY29udGVudD1zaWdudXAtd2VsY29tZSZ1dG1fY2FtcGFpZ249b25ib2FyZGluZ1wiLFwiaWRcIjpcIjU5ZWNmMjdhZjM4ZjRmOWM4NmFjNTJkMjU1OTcwZjVjXCIsXCJ1cmxfaWRzXCI6W1wiZjE3ODZlNmNlYzk3NTBkMmQzMDM3YWM1M2YyN2RmMGNkZjFlOTAwNFwiXX0ifQ&amp;source=gmail&amp;ust=1492817404667000&amp;usg=AFQjCNEYuvEQ3Rncp_AXCkS987NU39m9uA">Privacy
                                            Policy</a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>

                            </td>
                        </tr>
                        </tbody>
                    </table>

                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <img src="https://ci4.googleusercontent.com/proxy/-Yg0RqYWn2VpwgVlYqGHwNbS4i07iOPS3yrhGOoxrgnTiMUloQxYczBHxfcEUa1mWF7mexqb-zlui7IsXY9fFwS0TCcmQjm7lCjX5dYXuZ5hJRCXFEceC3UWcIIF5F08mlxr-_aHthD_r7y-KJhnmfA=s0-d-e1-ft#http://click.mailchimpapp.com/track/open.php?u=10612303&amp;id=59ecf27af38f4f9c86ac52d255970f5c"
         height="1" width="1">
</div>
</body>
</html>