<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 08/08/2017
 * Time: 12:34 PM
 */
?>
<div class="center-block w-xxl w-auto-xs">
    <div class="p-a-md box-color r text-color m-a">
        <div class="md-form-group float-label">
            <input name="pass" type="password" class="md-input" required>
            <label>PASSWORD</label>
        </div>
        <div class="md-form-group float-label">
            <input value="" name="api_key" type="text" class="md-input" required>
            <label>API KEY</label>
        </div>
        <div class="md-form-group float-label">
            <input value="" name="api_secret" type="text" class="md-input" required>
            <label>API SECRET</label>
        </div>
        <div>
            <a onclick="btnGuardar()" class="btn lime-600 btn-block p-x-md">Guardar</a>
        </div>
    </div>
</div>
