<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 05/abr/2017
 * Time: 12:56 PM
 */
/**
 * @var ordersController $controller
 */
?>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Amount</th>
        <th>Pesos</th>
        <th>Price</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <?= $controller->order ?>
    </tr>
    </tbody>
</table>
