INSERT INTO estados (nombre_estado) VALUES ('Aguascalientes');
INSERT INTO estados (nombre_estado) VALUES ('Baja California');
INSERT INTO estados (nombre_estado) VALUES ('Baja California Sur');
INSERT INTO estados (nombre_estado) VALUES ('Campeche');
INSERT INTO estados (nombre_estado) VALUES ('Chiapas');
INSERT INTO estados (nombre_estado) VALUES ('Chihuahua');
INSERT INTO estados (nombre_estado) VALUES ('Coahuila');
INSERT INTO estados (nombre_estado) VALUES ('Colima');
INSERT INTO estados (nombre_estado) VALUES ('Distrito Federal');
INSERT INTO estados (nombre_estado) VALUES ('Durango');
INSERT INTO estados (nombre_estado) VALUES ('Estado de México');
INSERT INTO estados (nombre_estado) VALUES ('Guanajuato');
INSERT INTO estados (nombre_estado) VALUES ('Guerrero');
INSERT INTO estados (nombre_estado) VALUES ('Hidalgo');
INSERT INTO estados (nombre_estado) VALUES ('Jalisco');
INSERT INTO estados (nombre_estado) VALUES ('Michoacán');
INSERT INTO estados (nombre_estado) VALUES ('Morelos');
INSERT INTO estados (nombre_estado) VALUES ('Nayarit');
INSERT INTO estados (nombre_estado) VALUES ('Nuevo León');
INSERT INTO estados (nombre_estado) VALUES ('Oaxaca');
INSERT INTO estados (nombre_estado) VALUES ('Puebla');
INSERT INTO estados (nombre_estado) VALUES ('Querétaro');
INSERT INTO estados (nombre_estado) VALUES ('Quintana Roo');
INSERT INTO estados (nombre_estado) VALUES ('San Luis Potosí');
INSERT INTO estados (nombre_estado) VALUES ('Sinaloa');
INSERT INTO estados (nombre_estado) VALUES ('Sonora');
INSERT INTO estados (nombre_estado) VALUES ('Tabasco');
INSERT INTO estados (nombre_estado) VALUES ('Tamaulipas');
INSERT INTO estados (nombre_estado) VALUES ('Tlaxcala');
INSERT INTO estados (nombre_estado) VALUES ('Veracruz');
INSERT INTO estados (nombre_estado) VALUES ('Yucatán');
INSERT INTO estados (nombre_estado) VALUES ('Zacatecas');